services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
  site:
    build:
      context: .
      dockerfile: site.Dockerfile
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - site
