services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
  site:
    build:
      context: .
      dockerfile: site.Dockerfile
    volumes:
      - static_files:/site/static/
      - media_files:/site/media/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - static_files:/var/www/static/
      - media_files:/var/www/media/
    ports:
      - 80:80
    depends_on:
      - site

volumes:
  postgres_data:
  static_files:
  media_files:
